### ISSUE TITLE
4张各12G的显卡仍然CUDA out of memory

### ISSUE THREAD

**Issue by fishfree** [OpenBMB/MiniCPM-V#102]
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 10.75 GiB of which 105.62 MiB is free. Including non-PyTorch memory, this process has 10.65 GiB memory in use. Of the allocated memory 10.49 GiB is allocated by PyTorch, and 1.63 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
我看模型文件很小啊。是不是还需要设置什么一个环境变量才能把4张卡都用起来？
先谢过各位了！

**Comment by iceflame89** [comment]
请提供下pytorch版本和推理代码

**Comment by fishfree** [comment]
@iceflame89 就是README里的代码。我换成了int4量化版后可以用了，可能还确实是显存不够吧。谢谢您！

**Comment by fishfree** [comment]
@CanvaChen 所以要是能支持多显卡就好了
