### ISSUE TITLE
[BUG] <MiniCPM-Llama3-V-2.5无法在24G 4090上启动>

### ISSUE THREAD

**Issue by weiminw** [OpenBMB/MiniCPM-V#288]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

按照你们在huggingface提供的sample，启动报错:

```
Loading checkpoint shards: 100%|██████████████████| 7/7 [00:02<00:00,  2.36it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/workspace/heliumos-bixi/heliumos-bixi-vision/tests/test_minicpmv.py", line 7, in <module>
    model.to(device='cuda')
  File "/workspace/heliumos-env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2724, in to
    return super().to(*args, **kwargs)
  File "/workspace/heliumos-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/workspace/heliumos-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/workspace/heliumos-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/workspace/heliumos-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/workspace/heliumos-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/workspace/heliumos-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU 
```

### 期望行为 | Expected Behavior

期望可以在4090上使用。

### 运行环境 | Environment

```Markdown
- OS: ubuntu 22.04
- Python: 3.10.2
- Transformers: 4.41.2
- PyTorch:2.3.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by 1SingleFeng** [comment]
请问这是训练还是推理

**Comment by weiminw** [comment]
> 请问这是训练还是推理

推理

**Comment by weiminw** [comment]
使用的测试代码就是huggfingface 首页提供的。

```
model = AutoModel.from_pretrained('openbmb/MiniCPM-Llama3-V-2_5', trust_remote_code=True, torch_dtype=torch.float16)
model = model.to(device='cuda')

tokenizer = AutoTokenizer.from_pretrained('openbmb/MiniCPM-Llama3-V-2_5', trust_remote_code=True)
model.eval()

image = Image.open('xx.jpg').convert('RGB')
question = 'What is in the image?'
msgs = [{'role': 'user', 'content': question}]

res = model.chat(
    image=image,
    msgs=msgs,
    tokenizer=tokenizer,
    sampling=True, # if sampling=False, beam_search will be used by default
    temperature=0.7,
    # system_prompt='' # pass system_prompt if needed
)
print(res)
```

**Comment by 1SingleFeng** [comment]
> 使用的测试代码就是huggfingface 首页提供的。
> 
> ```
> model = AutoModel.from_pretrained('openbmb/MiniCPM-Llama3-V-2_5', trust_remote_code=True, torch_dtype=torch.float16)
> model = model.to(device='cuda')
> 
> tokenizer = AutoTokenizer.from_pretrained('openbmb/MiniCPM-Llama3-V-2_5', trust_remote_code=True)
> model.eval()
> 
> image = Image.open('xx.jpg').convert('RGB')
> question = 'What is in the image?'
> msgs = [{'role': 'user', 'content': question}]
> 
> res = model.chat(
>     image=image,
>     msgs=msgs,
>     tokenizer=tokenizer,
>     sampling=True, # if sampling=False, beam_search will be used by default
>     temperature=0.7,
>     # system_prompt='' # pass system_prompt if needed
> )
> print(res)
> ```

那就不知道了，我也有台4090 24GB，还没测试过，如果后续测试有问题的话再联系你

**Comment by 1SingleFeng** [comment]
> odel = model.to(device='cuda')

你现在这个是显存不够报错，可以尝试将模型放在CPU上进行推理

**Comment by weiminw** [comment]
对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。

**Comment by 1SingleFeng** [comment]
> 对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。

不确定你这边出现了什么问题，我这边使用官方给的示例代码https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation，完全可以跑起来

**Comment by 1SingleFeng** [comment]
> > 对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。
> 
> 不确定你这边出现了什么问题，我这边使用官方给的示例代码[[https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation](https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation) ，完全可以跑起来

**Comment by Zhaojjjjjj** [comment]
> > 对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。
> 
> 不确定你这边出现了什么问题，我这边使用官方给的示例代码https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation ，完全可以跑起来

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openbmb/MiniCPM-Llama3-V-2_5-int4 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by Zhaojjjjjj** [comment]
> > 对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。
> 
> 不确定你这边出现了什么问题，我这边使用官方给的示例代码https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation ，完全可以跑起来

![1](https://github.com/OpenBMB/MiniCPM-V/assets/102017381/2490e92c-6db3-49dc-ba6c-d5666d5ed870)
大佬，这个怎么解决...

**Comment by 1SingleFeng** [comment]
> > > 对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。
> > 
> > 
> > 不确定你这边出现了什么问题，我这边使用官方给的示例代码https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation ，完全可以跑起来
> 
> ![1](https://private-user-images.githubusercontent.com/102017381/341332421-2490e92c-6db3-49dc-ba6c-d5666d5ed870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzIxMjQsIm5iZiI6MTcxODg3MTgyNCwicGF0aCI6Ii8xMDIwMTczODEvMzQxMzMyNDIxLTI0OTBlOTJjLTZkYjMtNDlkYy1iYTZjLWQ1NjY2ZDVlZDg3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwODIzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjYyYWU2YTQxMzE1OTVhZjY3ZDc1NTViZWJhNTIyMTIxMzZjMjE0Njc2ZjM4NTRlY2FiM2E1ZTk2MTQ2ZjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V947pckGPwfuneVebhe7Fu0aW7ft5oXpMUVvHYVeHqY) 大佬，这个怎么解决...

需要去huggingface下载minicpm-llama3-v-2_5的权重（下载地址 https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5），代码里指定权重路径，要不然会自动下载，但是看你的报错是本地网络不能连接huggingface，所以下载不了

**Comment by weiminw** [comment]
> > 对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。
> 
> 不确定你这边出现了什么问题，我这边使用官方给的示例代码https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation ，完全可以跑起来

我对比了一下， 加载model之后需要， model.to(dtype=torch.bfloat16) 这个是关键， 加了这个24G 就可以启动了。

**Comment by 1SingleFeng** [comment]
> > > 对，但是我看官方说法是 fp16 17-18G 显存， 我这24G启动不了，比较奇怪。
> > 
> > 
> > 不确定你这边出现了什么问题，我这边使用官方给的示例代码https://github.com/OpenBMB/MiniCPM-V#multi-turn-conversation ，完全可以跑起来
> 
> 我对比了一下， 加载model之后需要， model.to(dtype=torch.bfloat16) 这个是关键， 加了这个24G 就可以启动了。

了解了，感谢~

**Comment by weiminw** [comment]
问题已解决
